version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: rtc_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: manage_task_db
    ports:
      - "5432:5432"
    volumes:
      - rtc_postgres_data:/var/lib/postgresql/data

volumes:
  rtc_postgres_data: